### ISSUE TITLE
ETH Denver goals:

### ISSUE THREAD

**Issue by nickscavuzzo33** [oceanprotocol/df-issues#152] opened 2023-03-02 07:11 UTC

**Comment by idiom-bytes** [comment] 2023-03-10 22:59
@nickscavuzzo33 can you please expand on this or close it?

**Comment by jamiehewitt15** [comment] 2023-03-13 12:44
It's already done, no need for this to remain open. 

It's also a duplicate of https://github.com/oceanprotocol/df-issues/issues/153

**Closed as completed by jamiehewitt15** 2023-03-13 12:44 UTC
